name: CI for Kotlin multiplatform app
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build libraries and sample app
        run: ./gradlew assembleDebug